package com.example.meetbookadmin

const val EXTRA_ADMIN_DATA = "ADMINDATA123"
const val EXTRA_ROOM_ID = "ROOMID123"
const val EXTRA_ROOM_TITLE = "ROOMTITLE123"
const val EXTRA_ROOM_CAP = "ROOMCAP123"
const val EXTRA_ROOM_IMAGE = "ROOMIMAGE123"
const val EXTRA_UPDATE_ROOM_ID = "ROOMUID123"
const val EXTRA_UPDATE_ROOM_TITLE = "ROOMUTITLE123"
const val EXTRA_UPDATE_ROOM_CAP = "ROOMUCAP123"
const val EXTRA_UPDATE_ROOM_IMAGE = "ROOMUIMAGE123"
const val EXTRA_UPDATE_RESULT = 12346
